version: '3.8'

services:
  # Frontend - React Application
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: eccs-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://traefik:80
    depends_on:
      - traefik
    networks:
      - eccs-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`frontend.localhost`)"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"

  # Backend Email Service
  email-service:
    build:
      context: ./backend/email-service
      dockerfile: Dockerfile
    container_name: eccs-email-service
    environment:
      - NODE_ENV=production
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=eccs_email
      - POSTGRES_USER=eccs_user
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-eccs_secure_password}
      - KAFKA_BROKERS=kafka:9092
      - MONGODB_URI=mongodb://mongodb:27017/eccs_logs
      - JWT_SECRET=${JWT_SECRET:-your-super-secret-jwt-key}
      - JAEGER_ENDPOINT=http://jaeger:14268/api/traces
    depends_on:
      - postgres
      - kafka
      - mongodb
    networks:
      - eccs-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.email.rule=Host(`api.localhost`) && PathPrefix(`/api/emails`)"
      - "traefik.http.services.email.loadbalancer.server.port=3001"
      - "traefik.http.routers.email.middlewares=jwt-auth@file"
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M

  # Auth Service
  auth-service:
    build:
      context: ./backend/auth-service
      dockerfile: Dockerfile
    container_name: eccs-auth-service
    environment:
      - NODE_ENV=production
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=eccs_auth
      - POSTGRES_USER=eccs_user
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-eccs_secure_password}
      - JWT_SECRET=${JWT_SECRET:-your-super-secret-jwt-key}
      - JWT_EXPIRATION=1h
    depends_on:
      - postgres
    networks:
      - eccs-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth.rule=Host(`api.localhost`) && PathPrefix(`/api/auth`)"
      - "traefik.http.services.auth.loadbalancer.server.port=3002"

  # Notification Service (Kafka Consumer)
  notification-service:
    build:
      context: ./backend/notification-service
      dockerfile: Dockerfile
    container_name: eccs-notification-service
    environment:
      - NODE_ENV=production
      - KAFKA_BROKERS=kafka:9092
      - KAFKA_GROUP_ID=notification-group
      - MONGODB_URI=mongodb://mongodb:27017/eccs_logs
      - SMTP_HOST=${SMTP_HOST:-smtp.example.com}
      - SMTP_PORT=${SMTP_PORT:-587}
      - SMTP_USER=${SMTP_USER:-user@example.com}
      - SMTP_PASS=${SMTP_PASS:-password}
      - RETRY_ATTEMPTS=3
      - RETRY_DELAY=5000
      - JAEGER_ENDPOINT=http://jaeger:14268/api/traces
    depends_on:
      - kafka
      - mongodb
    networks:
      - eccs-network
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: eccs-postgres
    environment:
      - POSTGRES_USER=eccs_user
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-eccs_secure_password}
      - POSTGRES_MULTIPLE_DATABASES=eccs_email,eccs_auth
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/postgres/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - eccs-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U eccs_user"]
      interval: 10s
      timeout: 5s
      retries: 5

  # MongoDB for Logging
  mongodb:
    image: mongo:6
    container_name: eccs-mongodb
    volumes:
      - mongodb_data:/data/db
      - ./database/mongodb/init:/docker-entrypoint-initdb.d
    ports:
      - "27017:27017"
    networks:
      - eccs-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Kafka
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: eccs-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - zookeeper_data:/var/lib/zookeeper/data
    networks:
      - eccs-network

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: eccs-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - eccs-network

  # Traefik API Gateway
  traefik:
    image: traefik:v3.0
    container_name: eccs-traefik
    command:
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file.directory=/etc/traefik/dynamic"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--log.level=INFO"
      - "--accesslog=true"
      - "--tracing.jaeger=true"
      - "--tracing.jaeger.samplingServerURL=http://jaeger:5778/sampling"
      - "--tracing.jaeger.localAgentHostPort=jaeger:6831"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./infrastructure/traefik:/etc/traefik/dynamic
    networks:
      - eccs-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.localhost`)"
      - "traefik.http.routers.dashboard.service=api@internal"

  # ELK Stack - Elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: eccs-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - eccs-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  # ELK Stack - Logstash
  logstash:
    image: docker.elastic.co/logstash/logstash:8.11.0
    container_name: eccs-logstash
    volumes:
      - ./infrastructure/elk/logstash/pipeline:/usr/share/logstash/pipeline
      - ./infrastructure/elk/logstash/config:/usr/share/logstash/config
    ports:
      - "5044:5044"
      - "5000:5000"
    environment:
      - "LS_JAVA_OPTS=-Xms256m -Xmx256m"
    depends_on:
      - elasticsearch
    networks:
      - eccs-network

  # ELK Stack - Kibana
  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.0
    container_name: eccs-kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - eccs-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kibana.rule=Host(`kibana.localhost`)"
      - "traefik.http.services.kibana.loadbalancer.server.port=5601"

  # Grafana Monitoring
  grafana:
    image: grafana/grafana:10.2.0
    container_name: eccs-grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD:-admin123}
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
      - ./infrastructure/grafana/provisioning:/etc/grafana/provisioning
      - ./infrastructure/grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - "3030:3000"
    depends_on:
      - prometheus
    networks:
      - eccs-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`grafana.localhost`)"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"

  # Prometheus for metrics
  prometheus:
    image: prom/prometheus:v2.47.0
    container_name: eccs-prometheus
    volumes:
      - ./infrastructure/grafana/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    networks:
      - eccs-network

  # Jaeger for Distributed Tracing
  jaeger:
    image: jaegertracing/all-in-one:1.51
    container_name: eccs-jaeger
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686"
      - "14268:14268"
      - "6831:6831/udp"
    networks:
      - eccs-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jaeger.rule=Host(`jaeger.localhost`)"
      - "traefik.http.services.jaeger.loadbalancer.server.port=16686"

networks:
  eccs-network:
    driver: bridge

volumes:
  postgres_data:
  mongodb_data:
  zookeeper_data:
  kafka_data:
  elasticsearch_data:
  grafana_data:
  prometheus_data:
