# ============================================================================
# Kibana Configuration for ECCS Platform
# ============================================================================
# Configuration for the Kibana visualization layer of the ELK stack.
# Optimized for ECCS logging and monitoring use cases.
# ============================================================================

# -----------------------------------------------------------------------------
# Server Settings
# -----------------------------------------------------------------------------
# Bind to all interfaces (required for container networking)
server.host: "0.0.0.0"
# Port to listen on
server.port: 5601
# Server name (displayed in UI)
server.name: "eccs-kibana"

# Base path if behind a reverse proxy (Traefik)
# Uncomment if using URL like https://domain.com/kibana/
# server.basePath: "/kibana"
# server.rewriteBasePath: true

# Maximum payload size
server.maxPayload: 1048576

# -----------------------------------------------------------------------------
# Elasticsearch Connection
# -----------------------------------------------------------------------------
# Elasticsearch hosts (can be array for multiple nodes)
elasticsearch.hosts: ["http://elasticsearch:9200"]

# Connection timeout
elasticsearch.requestTimeout: 30000
# Ping timeout
elasticsearch.pingTimeout: 30000

# Elasticsearch authentication (if security is enabled)
# elasticsearch.username: "kibana_system"
# elasticsearch.password: "${ELASTICSEARCH_PASSWORD}"

# SSL/TLS settings for Elasticsearch connection
# elasticsearch.ssl.verificationMode: full
# elasticsearch.ssl.certificateAuthorities: ["/path/to/ca.crt"]

# -----------------------------------------------------------------------------
# Security Settings
# -----------------------------------------------------------------------------
# X-Pack security (matches Elasticsearch security settings)
xpack.security.enabled: false

# Encryption keys for saved objects
# Use strong random keys in production
# xpack.encryptedSavedObjects.encryptionKey: "32-character-encryption-key-here"
# xpack.reporting.encryptionKey: "32-character-encryption-key-here"
# xpack.security.encryptionKey: "32-character-encryption-key-here"

# -----------------------------------------------------------------------------
# Logging Settings
# -----------------------------------------------------------------------------
# Log level
logging.root.level: info

# Log to stdout (container best practice)
logging.appenders.default:
  type: console
  layout:
    type: json

logging.root.appenders:
  - default

# -----------------------------------------------------------------------------
# Monitoring Settings
# -----------------------------------------------------------------------------
# Enable monitoring data collection
monitoring.ui.enabled: true
monitoring.ui.container.elasticsearch.enabled: true

# -----------------------------------------------------------------------------
# UI Settings
# -----------------------------------------------------------------------------
# Default route on login
# uiSettings.overrides.defaultRoute: "/app/discover"

# Dark mode by default
# uiSettings.overrides."theme:darkMode": true

# Default time range
uiSettings.overrides.timepicker:defaultTimeRange:
  from: "now-24h"
  to: "now"

# Default time zone
uiSettings.overrides.dateFormat:tz: "UTC"

# -----------------------------------------------------------------------------
# Telemetry Settings
# -----------------------------------------------------------------------------
# Disable telemetry (optional)
telemetry.enabled: false
telemetry.optIn: false

# -----------------------------------------------------------------------------
# NewsFeed Settings
# -----------------------------------------------------------------------------
# Disable news feed (optional)
newsfeed.enabled: false

# -----------------------------------------------------------------------------
# Fleet / Elastic Agent Settings
# -----------------------------------------------------------------------------
# Disable Fleet integration and Elastic Package Registry connection.
# This prevents Kibana from trying to connect to epr.elastic.co which causes
# errors in air-gapped environments or when behind a proxy.
# The ECCS platform uses Kibana only for log visualization, not Fleet/Elastic Agent.
xpack.fleet.isAirGapped: true
